# ---- Unix ----
# systemctl docker start
# docker run --rm --interactive --tty --volume #PWD:/app composer create-project --ignore-platform-reqs --no-dev codelinered/vue-skeleton vue-skeleton "dev-production" && cd vue-skeleton && docker-compose up -d && xdg-open http://localhost:7702

# ---- Windows CMD ----
# "C:\Program Files\Docker\Docker Desktop.exe"
# docker run --rm --interactive --tty --volume %cd%:/app composer create-project --ignore-platform-reqs --no-dev codelinered/vue-skeleton vue-skeleton "dev-production" && cd vue-skeleton && docker-compose up -d && start http://localhost:7702

volumes:
    logs:
        driver: local

# ---- Unix ----
# docker-compose up -d && xdg-open http://localhost:7702
# ---- Windows CMD ----
# docker-compose up -d && start http://localhost:7702
services:
    # http://localhost:7702
    # docker exec -ti vue-skeleton php --version
    webserver:
        image: php:8-alpine
        container_name: vue-skeleton
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t public
        environment:
            docker: "true"
        ports:
            - 7702:80
        volumes:
            - .:/var/www
            - logs:/var/www/logs
